package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/madsilver/template-bff/internal/adapter/mappers"
	"github.com/madsilver/template-bff/internal/adapter/presenter"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*presenter.Health, error) {
	ent, err := r.HealthUseCase.Check(ctx)
	return mappers.HealthPresenter(ent), err
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
