// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package presenter

type Health struct {
	Message    string `json:"message"`
	StatusCode int    `json:"status_code"`
}

type Query struct {
}
