receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://0.0.0.0:9411/api/v2/spans"
  prometheusremotewrite:
    endpoint: "http://0.0.0.0:9464"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]

    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
      processors: [batch]